---
# defaults file for roles/docker
---
docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

